---
- name: Configure Nginx
  hosts: reddit-app
  become: true

  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        puma:
          - listen 80
          - server_name _
          - root "/usr/share/nginx/html"
          - index index.html
          - location / { proxy_pass http://127.0.0.1:9292; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
